language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
notifications:
  email:
    on_success: never
    on_failure: change
before_install: npm install -g grunt-cli
install: npm install
